services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:8080
    depends_on:
      - server
    container_name: my-app-frontend

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://mongo:27017/myapp
      - PORT=3001
    depends_on:
      - mongo
    container_name: my-app-backend

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    container_name: my-app-mongo

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app
      - server
    container_name: my-app-nginx

volumes:
  mongo_data:
